# This is a basic workflow to help you get started with Actions

name: Deploy Selfhost

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: ${{secrets.ANSIBLE_DELOY_REPOSITORY}}

      # Runs a single command using the runners shell
      - name: Run deploy workflow
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ./
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [workflow-server]
            ${{secrets.SSH_HOST}}
          options: |
            -u ${{secrets.SSH_REMOTE_USER}}
            --tags=workflow
            --verbose

      # Runs a set of commands using the runners shell
      - name: Finish
        run: |
          echo Finish deploy
